server:
  port: 9002

spring:
  profiles:
    active:
      - native
  cloud:
    config:
      server:
        native:
          search-locations:
            - 'classpath:/config'
            - 'classpath:/config/{application}'
