# Default configuration for H2

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:${h2.database}
    driver-class-name: org.h2.Driver
    username: ${h2.username}
    password: ${h2.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: on
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: on
  sql:
    init:
      platform: h2
      mode: always
