# Default configuration for Postgres

spring:
  datasource:
    url: ${postgres.database}
    driver-class-name: org.postgresql.Driver
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    placeholders:
      db_user: ${postgres.username}
