# Default configuration for H2

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:${h2.database}
    driver-class-name: org.h2.Driver
    username: ${h2.username}
    password: ${h2.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    url: jdbc:h2:mem:${h2.database};DB_CLOSE_DELAY=-1
    user: ${h2.username}
    password: ${h2.password}
    baseline-on-migrate: true
    placeholders:
      db_user: ${h2.username}

