name: Release Docker

env:
  DOCKER_HUB_LOGIN: anthonyjhoiro
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-release:
    name: Docker deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - path: back/user-service
          context: back
          image: anthonyjhoiro/talky_user-service

        - path: back/admin-server
          context: back
          image: anthonyjhoiro/talky_admin-server

        - path: back/config-server
          context: back
          image: anthonyjhoiro/talky_config-server

        - path: back/gateway
          context: back
          image: anthonyjhoiro/talky_gateway


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get image tags
        run: |
          IMAGE_NAME=${{ matrix.module.image }}

          echo "Event Type = ${GITHUB_EVENT_NAME}"

          if [ ${GITHUB_EVENT_NAME} = "workflow_dispatch" ]; then
            IMAGES="${IMAGE_NAME}:preview-${{github.run_number}}"
          else
            IMAGES="${IMAGE_NAME}:latest,${IMAGE_NAME}:${GITHUB_REF##*/}"
          fi
          echo "::set-output name=tags::$IMAGES"
        id: image_name


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: anthonyjhoiro
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./${{ matrix.module.path }}
          tags: ${{ steps.image_name.outputs.tags }}
