name: Release Docker Back

env:
  DOCKER_HUB_LOGIN: anthonyjhoiro
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  PREFIX: talky

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      name:
        required: true
        description: Preview Build name
        default: "1"
        type: string

jobs:
  docker-release:
    name: Docker deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    strategy:
      matrix:
        module:
        - admin-server
        - config-server
        - gateway
        - user-service

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get image tags
        run: |
          IMAGE_NAME="${DOCKER_HUB_LOGIN}/${PREFIX}_$(basename ${{ matrix.module }})"

          echo "Event Type = ${GITHUB_EVENT_NAME}"

          if [ ${GITHUB_EVENT_NAME} = "workflow_dispatch" ]; then
            IMAGES="${IMAGE_NAME}:preview-${{ github.event.inputs.name }}"
          else
            IMAGES="${IMAGE_NAME}:latest,${IMAGE_NAME}:${GITHUB_REF##*/}"
          fi
          echo "::set-output name=tags::$IMAGES"
        id: image_name

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: anthonyjhoiro
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./back
          build-args: MODULE=${{ matrix.module }}
          tags: ${{ steps.image_name.outputs.tags }}
