name: Release Docker

env:
  DOCKER_HUB_LOGIN: anthonyjhoiro
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  PREFIX: talky

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-release:
    name: Docker deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - talky-front
        - user-service

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get image name and tag
        run: |
          echo "::set-output name=image_name::${DOCKER_HUB_LOGIN}/${PREFIX}_$(basename ${{ matrix.module }})"
          echo "::set-output name=tag_name::${GITHUB_REF##*/}"
        id: image_name

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: anthonyjhoiro
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: Build ${{ matrix.module }}
        if: hashfile('build-docker-${{ matrix.module }}.yml') != ''
        uses: ./.github.workflows/build-docker-${{ matrix.module }}.yml

#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          context: ./${{ matrix.module }}
#          tags: |
#            ${{ steps.image_name.outputs.image_name }}:latest
#            ${{ steps.image_name.outputs.image_name }}:${{ steps.image_name.outputs.tag_name }}
